Metrics refactor
amanyazevedoamin/ViewBasedNavigation pull request #1
Opened 2022-03-28 14:50 UTC by efkag

Added code for the Sig2Noise ration and Sig2 Integral ratio.
The Gaussian method required the implementation of an MSe loss

2022-03-28 14:51 UTC, efkag commented
@amanyazevedoamin We should add the __pycache__ folder to the git ignore probably

2022-03-28 14:58 UTC, efkag commented
> @amanyazevedoamin We should add the **pycache** folder to the git ignore probably

Nevermind I just saw that you have added onto the gitignore that is on master but I branched out earlier

2022-03-29 11:18 UTC, amanyazevedoamin requested changes
Thanks for these! Please see the comments, mainly about removing the old SNR code - then I'm happy to merge.

2022-03-29 11:18 UTC, amanyazevedoamin commented on QualityMetrics.py
>  # Specify the Butterworth Filter
Happy for you to delete the old SNR stuff

2022-03-29 11:18 UTC, amanyazevedoamin commented on examples/snr-example.py
> +snr = Sig2Noise().Fit()
Sig2Noise doesn't need the .Fit() called right? Shouldn't it be like the example below, with just setting up the object and calling .Eval

2022-03-29 11:18 UTC, amanyazevedoamin commented on QualityMetrics.py
> +#TODO: The frist 2 metric may need to implemented such that we process multiple RFs
At the point of processing RRFFs, I stopped doing parallel operations because things were so fast anyway. E..g on my machine it takes ~ 1 second to get the SNR for 100 RRFFs through list comp. So maybe something to consider in future if we are going thousands and thousands of RRFFs? But certainly not something to worry about at the present moment.

2022-03-29 13:48 UTC, amanyazevedoamin approved these changes

2022-03-30 13:07 UTC, efkag commented on QualityMetrics.py
>  # Specify the Butterworth Filter
Done

2022-03-30 13:08 UTC, efkag commented on QualityMetrics.py
> +#TODO: The frist 2 metric may need to implemented such that we process multiple RFs
We can indeed easily refactor this coed in the future to handle multiple RFs.

2022-03-30 13:09 UTC, efkag commented on examples/snr-example.py
> +snr = Sig2Noise().Fit()
Yes Fit() is useless in this case but I used it there to demonstrate that it can be used safely without breaking anything.
For some of the other metrics this function will actually fir the RFs.

2022-03-30 13:29 UTC, merged